---

# ************Tasks file for Aruba "configuration" *******************

# **************************************************************************
#       Login with enterprise Profile
# **************************************************************************
- name: Assign Device to Customer
  uri:
    url: "{{ url }}/msp_api/v1/customers/{{ customer_id }}/devices"
    method: PUT
    body: '{"devices":[{"serial":"{{ device_serial_id }}","mac":"{{ device_mac_address }}"}]}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- debug:
    msg: "MKA  {{ response.content | to_json }}"