---
# tasks file for velocloud "configurationId"
- name: Get Config id from enterprise Profile
  vars:
    body: "{{ lookup('template','../files/loginRequest.json') | to_json }}"
  uri:
    url: "{{ veloURL }}/enterprise/getEnterpriseConfigurations"
    method: POST
    username: "{{ username }}"
    password: "{{ password }}"
    body: "{{ body }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
      Accept: "application/json"
  register: response
- debug:
    msg: "{{  response}} "