---
# ************Tasks file for velocloud "configurationId" *******************

# **************************************************************************
#       Login with enterprise Profile
# **************************************************************************
- name: Login with enterprise Profile
  vars:
    body: "{{ lookup('template','../files/loginRequest.txt') }}"
  uri:
    url: "{{ veloURL }}/login/enterpriseLogin"
    method: POST
    body: "{{ body }}"
    force_basic_auth: yes
    status_code: 200
    body_format: raw
    validate_certs: false
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: response
- set_fact:
    cookies_id: "{{ response.cookies}}"
- debug:
    msg: " reqest {{cookies_id}} "

# **************************************************************************
#        Get Configurations from enterprise Profile
# **************************************************************************
- name: Get Config id from enterprise Profile
  vars:
    body: "{{ lookup('template','../files/getEnterpriseConfRequest.json') | to_json }}"
  uri:
    url: "{{ veloURL }}/enterprise/getEnterpriseConfigurations"
    method: POST
    body: "{{ body }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Cookie: "culture=en-US;velocloud.session={{ cookies_id['velocloud.session'] }}"
  register: response
#- set_fact:
    # configurationId: "{{ response.json[2].id }}"
    #configurationId: "{{ item.id }}" 
  #with_items: "{{ response.json }}"
  #when: item.name == 'Accenture Lab Profile'
- debug:
    msg: "Profile id for vpn profile-   {{  response.content  }} "

# **************************************************************************
#       Provision the Edge Device
# **************************************************************************
- name: Provision Edge Device
  vars:
    body: "{{ lookup('template','../files/edgeProvisionRequest.json') | to_json }}"
  uri:
    url: "{{ veloURL }}/edge/edgeProvision"
    method: POST
    user: "{{ username }}"
    password: "{{ password }}"
    body: "{{ body }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- set_fact:
    velo_edge_id: "{{ response.json.id }}"
    Req: "{{ lookup('template','../files/edgeProvisionRequest.json') | to_json }}"
- debug:
    msg: "Request {{ Req }} --  MKA  {{ velo_edge_id }} Provisioned "

# **************************************************************************
#       Login with enterprise Profile
# **************************************************************************
- name: Update Devicesetting Module data for Edge
  debug:
        #msg: "{{ 'test' | another_filter('one','two')}}"
    msg: "{{ velo_edge_id | updateDeviceSettings(configurationId) }}"