---
# tasks file for velocloud "configurationId"
- name: Get Config id from enterprise Profile
  vars:
    body: "{{ lookup('template','../files/loginRequest.txt') }}"
  uri:
    url: "{{ veloURL }}/login/enterpriseLogin"
    method: POST
    body: "{{ body }}"
    force_basic_auth: yes
    status_code: 200
    body_format: raw
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: response
- set_fact:
    velo_edge_id: "{{ lookup('template','../files/loginRequest.txt') }}"
- debug:
    msg: " reqest {{velo_edge_id}} - {{  response}} "