---
# ************Tasks file for velocloud "configurationId" *******************

# **************************************************************************
#       Login with enterprise Profile
# **************************************************************************
- name: Login with enterprise Profile
  vars:
    body: "{{ lookup('template','../files/loginRequest.txt') }}"
  uri:
    url: "{{ veloURL }}/login/enterpriseLogin"
    method: POST
    body: "{{ body }}"
    force_basic_auth: yes
    status_code: 200
    body_format: raw
    validate_certs: false
    return_content: yes
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: response
- set_fact:
    cookies_id: "culture=en-US;velocloud.session={{ (response.cookies| length > 0) | ternary(response.cookies['velocloud.session'], 'empty') }}"
- debug:
    msg: " Logged in successfully!!  {{ lookup('template','../files/loginRequest.txt') }} "