---
# vars file for velocloud
enterpriseId: "{{ enterprise_ID }}"
#"configurationId": 2
QOS: "{{ qos }}"
username: "{{ user }}"
password: "{{ pass }}"

policy:
    id:"{{ id }}"
    policy:"{{ policy}}"

protocol:
    id:"{{ id }}"
    protocol:"{{ protocol }}"

rules:
    destApp:"{{ destApp }}"
    destId:"{{ destId }}"
    id:"{{ id }}"
    ruleName:"{{ ruleName }}"
    destAppIP:"{{ destAppIP }}"
    destAppPort:"{{ destAppPort }}"
    priority:"{{ priority }}"
    serviceClass:"{{ serviceClass }}"
    source:"{{ source }}"
    sourcePort:"{{ sourcePort }}"
    upLimit:"{{ upLimit }}"
    downLimit:"{{ downLimit }}"
    priorityID:"{{ priorityID }}"
    policy:"{{ policy }}"
    protocol:"{{ protocol }}"

segments: 
    segmentid:"{{ segmentid }}"
    segment:"{{ segment }}"
    rules:"{{ rules }}"
    subnet:"{{ subnet }}"
    cidr:"{{ cidr }}"

testVars:
    enterpriseId:"{{ enterpriseId }}",
    siteName:"{{ siteName }}",
    segments:"{{ segments }}",
    velo_edge_id:"{{ velo_edge_id }}"