---
- name: Patch template
  uri:
    url: "{{ url }}/configuration/v1/devices/DZ0005126/template_variables"
    method: POST
    #user: "{{ username }}"
    #password: "{{ password }}"
    #body: "{{ lookup('file','../files/create_customer.json') }}"
    body: '{"total":0,"variables":{"variable_name":"{{ tvar1 }}"}}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
  #register: request
- debug:
    msg: "MKA {{ response.content }} | to_json "

