---
- name: Patch template
  uri:
    url: "{{ url }}/configuration/v1/devices/{{  device_serial_id  }}/template_variables"
    method: POST
    #user: "{{ username }}"
    #password: "{{ password }}"
    #body: "{{ lookup('file','../files/create_customer.json') }}"
    body: '{"total":0,"variables":{"user_wlan":"{{ userwlan }}","corp_wlan":"{{ corpwlan }}","user_wlan_bw":"{{ userwlanbw }}","corp_wlan_bw":"{{ corpwlanbw }}","user_wlanqos":"{{ userwlanqos }}","corp_wlanqos":"{{ corpwlanqos }}" }}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
  #register: request
- set_fact:
    requestBody: "{{ uri.body }}" 
- debug:
    msg: "MKA {{ requestBody }} -- {{ response.content }} | to_json "