---
- name: Patch template
  vars:
    body: "{{ lookup('template','../files/patch_template_variables.json') | to_json }}"
  uri:
    url: "{{ url }}/configuration/v1/devices/{{  device_serial_id  }}/template_variables"
    method: POST
    #user: "{{ username }}"
    #password: "{{ password }}"
    body: "{{ body }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
  #register: request
- set_fact:
    my: "{{ lookup('template','../files/patch_template_variables.json')  }}"
- debug:
    msg: "Response: {{ response.content }} | to_json "