---
- name: Patch template
  vars:
    bod: "{{ lookup('template','../files/patch_template_variables.json') | to_json }}"
  uri:
    url: "{{ url }}/configuration/v1/devices/{{  device_serial_id  }}/template_variables"
    method: POST
    #user: "{{ username }}"
    #password: "{{ password }}"
    #body: "{{ lookup('file','../files/create_customer.json') }}"
    body: "{{ bod }}"
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: bod
  #register: request
- debug:
    msg: "MKA {{ bod }} | to_json "