---
- name: Login  
  uri:    
    url: "{{ url }}/oauth2/authorize/central/api/login?client_id={{ clientID }}"
    method: POST
    body: '{"username": "{{ user }}","password": "{{ pass }}"}'
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/stuff+json"
  register: response
- set_fact:
    csrf: "csrftoken={{ response.cookies['csrftoken'] }};Secure; Path=/"
    session: "session={{ response.cookies['session'] }}; Secure; HttpOnly; Path=/"
    csrf1: "{{ response.cookies['csrftoken'] }}"
    #session1: "{{ response.cookies['session'] }}"
- debug:
    msg: "MKA  {{ response }}"
- name: Get Auth Code
  uri:
    url: "{{ url }}/oauth2/authorize/central/api/?client_id={{ clientID }}&response_type=code&scope=all"
    method: POST
    body: '{}'    
    status_code: 200
    body_format: json
    force_basic_auth: yes
    validate_certs: false
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      X-Csrf-Token: "{{ csrf1 }}"
      Cookie: "{{ csrf }};{{ session }}"
      #session: "{{ session1 }}"
  register: response
- set_fact:
    authCode: "{{ response.json.auth_code }}"
- debug:
    msg: "Auth Code:  {{ authCode }}"
- name: Get Refresh Token
  uri:
    url: "{{ url }}/oauth2/token?client_id={{ clientID }}&grant_type=authorization_code&scope=all&client_secret={{ clientSecret }}&code={{ authCode }}"
    method: POST    
    body: '{}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- set_fact:
    refreshToken: "{{ response.json.refresh_token }}"
- debug:
    msg: "Refresh Token:  {{ refreshToken }}"
- name: Get Access Token
  uri:
    url: "{{ url }}/oauth2/token?client_id={{ clientID }}&client_secret={{ clientSecret }}&grant_type=refresh_token&refresh_token={{ refreshToken }}"
    method: POST
    body: '{}'    
    status_code: 200
    body_format: json
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- set_fact:
    accessToken: "{{ response.json.access_token }}"
- debug:
    msg: "Access Token  {{ accessToken }}"
- name: Get Monitoring API
  uri:
    url: "{{ url }}/monitoring/v1/aps?access_token={{ accessToken }}"
    method: GET
    body: '{}'    
    status_code: 200
    body_format: json
    force_basic_auth: yes
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- debug:
    msg: "MKA  {{ response.content | to_json }}"