---
- name: Login
  vars:
    body: "{{ lookup('template','../files/loginRequest.json') | to_json }}"
  uri:
    #url: "URL:http://services.groupkt.com/state/get/IND/KA"
    url: "https://apigw-prod2.central.arubanetworks.com/oauth2/authorize/central/api/login?client_id=iFztCEnFlccPAkGKlpDF3Ua4IV1G9wYy"
    method: POST
    body: '{"username": "r.madhur.ramachandra@accenture.com","password": "Admin1234"}'
    force_basic_auth: no
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- set_fact:
    csrf: "X-CSRF-Token={{ response.cookies['csrftoken'] }}"
    session: "session={{ response.cookies['session'] }}"
- debug:
    msg: "MKA  {{ response }}"
- name: Get Auth Code
  uri:
    url: "https://apigw-prod2.central.arubanetworks.com/oauth2/authorize/central/api/?client_id=iFztCEnFlccPAkGKlpDF3Ua4IV1G9wYy&response_type=code&scope=all"
    method: POST
    body: '{}'    
    status_code: 200
    body_format: json
    force_basic_auth: yes
    validate_certs: false
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
      Cookie: "{{ session }} {{ csrf }} Content-Length: ??"    
  register: response
- debug:
    msg: "MKA  {{ response.content | to_json }}"
- name: Create template group
  uri:
    url: "{{ url }}/configuration/v1/groups"
    method: POST
    #user: "{{ username }}"
    #password: "{{ password }}"
    #body: "{{ lookup('file','../files/create_customer.json') }}"
    body: '{"group":"{{ template_group }}","group_attributes":{"group_password":"{{ group_pwd }}","template_group":true}}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- debug:
    msg: "MKA  {{ response.content | to_json }}"
- name: Move device to template group
  uri:
    url: "{{ url }}/configuration/v1/devices/move"
    method: POST
    #user: "{{ username }}"
    #password: "{{ password }}"
    #body: "{{ lookup('file','../files/create_customer.json') }}"
    body: '{"group": "{{ template_group }}","serials":["{{ device_serial_id }}"]}'
    force_basic_auth: yes
    status_code: 200
    body_format: json
    validate_certs: no
    return_content: yes
    headers:
      Content-Type: "application/json"
      Accept: "application/json"
  register: response
- debug:
    msg: "MKA  {{ response.content | to_json }}"