# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PR Line Tracker

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  track-lines:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures Git diff can work correctly
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run Line Tracker Script
      run: |
        python scripts/line_tracker.py
        
    - name: Run Copilot Line Tracker Script
      run: |
        python scripts/Copilot_line_tracker.py
        
    - name: Sep 2 - Run Copilot Block Line Tracker Script
      id: codeCheck
      run: |
        python scripts/Copilot_block_tracker.py
        
    - name: Step3 - Update to Jira
      run: |
        python scripts/Update_Jira.py
      env:
        LINES_OF_CODE: ${{ steps.codeCheck.outputs.LinesOfCode }}
        COPILOT_LINES_OF_CODE: ${{ steps.codeCheck.outputs.CopilotLinesOfCode }}
